#!/usr/bin/env python3
"""BioData — dataset analysis skill for BioResearchOS.

Input: CSV / TSV / XLSX. Output:
  report.md + report.html   summary, missing values, descriptive stats
  tables/*.csv              summary, describe, correlation
  figures/*.png             histograms, correlation heatmap, PCA
  result.json               structured summary
  notebook.ipynb            minimal reproducible notebook

Requires: pandas, numpy, matplotlib, scikit-learn (all in project venv).
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA

plt.rcParams["figure.dpi"] = 150
plt.rcParams["savefig.bbox"] = "tight"


def read_input(path: Path) -> pd.DataFrame:
    if path.suffix.lower() == ".tsv":
        return pd.read_csv(path, sep="\t")
    if path.suffix.lower() == ".xlsx":
        return pd.read_excel(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    raise ValueError(f"unsupported input type: {path.suffix}")


def numeric_cols(df: pd.DataFrame) -> list[str]:
    return df.select_dtypes(include=[np.number]).columns.tolist()


def to_md(df: pd.DataFrame, title: str) -> str:
    if df.empty:
        return f"## {title}\n\n_none_\n"
    return (f"## {title}\n\n"
            + "| " + " | ".join(str(c) for c in df.columns) + " |\n"
            + "| " + " | ".join(["---"] * len(df.columns)) + " |\n"
            + "".join("| " + " | ".join(str(v) for v in row) + " |\n"
                      for row in df.itertuples(index=False))
            + "\n")


def analyze(df: pd.DataFrame, out: Path) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    figs = out / "figures"
    tbls = out / "tables"
    figs.mkdir(exist_ok=True)
    tbls.mkdir(exist_ok=True)

    num = numeric_cols(df)
    missing = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "missing": df.isna().sum().values,
    })
    missing["missing_pct"] = (missing["missing"] / len(df) * 100).round(2)

    desc = df[num].describe().T if num else pd.DataFrame()
    if not desc.empty:
        desc.insert(0, "statistic", desc.index.astype(str))
    corr = df[num].corr() if len(num) > 1 else pd.DataFrame()

    figure_paths = []
    for col in num:
        fig, ax = plt.subplots(figsize=(7, 5))
        bins = min(30, int(np.sqrt(len(df))) + 1)
        ax.hist(df[col].dropna(), bins=bins, edgecolor="white")
        ax.set_title(col)
        fig.savefig(figs / f"hist_{col}.png")
        plt.close(fig)
        figure_paths.append(f"figures/hist_{col}.png")

    if len(num) > 1:
        fig, ax = plt.subplots(figsize=(7, 5))
        im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
        ax.set_xticks(range(len(corr)), corr.columns, rotation=90)
        ax.set_yticks(range(len(corr)), corr.columns)
        fig.colorbar(im, ax=ax, fraction=0.046)
        ax.set_title("Correlation Matrix")
        fig.savefig(figs / "correlation.png")
        plt.close(fig)
        figure_paths.append("figures/correlation.png")

        X = df[num].dropna()
        if len(X) >= 2:
            fig, ax = plt.subplots(figsize=(7, 5))
            pca = PCA(n_components=min(2, len(num)))
            coords = pca.fit_transform(X)
            var = pca.explained_variance_ratio_
            ax.scatter(coords[:, 0], coords[:, 1], s=18, alpha=0.6)
            ax.set_title(f"PCA — PC1 {var[0]:.1%}, PC2 {var[1]:.1%} of variance")
            ax.set_xlabel("PC1")
            ax.set_ylabel("PC2")
            fig.savefig(figs / "pca.png")
            plt.close(fig)
            figure_paths.append("figures/pca.png")

    for name, dfx in [("summary", missing), ("describe", desc), ("correlation", corr)]:
        if not dfx.empty:
            dfx.to_csv(tbls / f"{name}.csv", index=False)

    result = {
        "rows": int(len(df)),
        "columns": int(len(df.columns)),
        "dtypes": {str(c): str(t) for c, t in df.dtypes.items()},
        "missing_total": int(df.isna().sum().sum()),
        "numeric_columns": num,
        "figures": figure_paths,
    }
    (out / "result.json").write_text(json.dumps(result, indent=2))

    md = (f"# BioData Report\n\n"
          f"{result['rows']} rows x {result['columns']} columns\n\n"
          + to_md(missing, "Missing values")
          + to_md(desc, "Descriptive statistics")
          + to_md(corr, "Correlation matrix")
          + "## Figures\n\n" + "\n".join(f"![{f}]({f})" for f in figure_paths)
          + "\n\n---\n*Generated by BioData (BioResearchOS). Research/educational use only.*\n")
    (out / "report.md").write_text(md)
    (out / "report.html").write_text(
        f"<html><body><h1>BioData Report</h1><pre>{md}</pre></body></html>")

    nb = {
        "cells": [{
            "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": "import json, pathlib\nprint(json.loads(pathlib.Path('result.json').read_text()))\n",
        }],
        "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3"},
                     "language_info": {"name": "python"}},
        "nbformat": 4, "nbformat_minor": 5,
    }
    (out / "notebook.ipynb").write_text(json.dumps(nb, indent=1))
    return result


def demo_df() -> pd.DataFrame:
    rng = np.random.default_rng(42)
    n = 200
    x = rng.normal(5, 1.5, n)
    df = pd.DataFrame({
        "sample_id": [f"S{i:03d}" for i in range(n)],
        "expression": x.round(3),
        "response": (x * 0.8 + rng.normal(0, 0.8, n)).round(3),
        "dose": rng.uniform(0.5, 20.0, n).round(2),
        "group": rng.choice(["control", "treated"], n),
    })
    for col in ["expression", "response", "dose"]:
        idx = rng.choice(n, 4, replace=False)
        df.loc[idx, col] = np.nan
    return df


def main():
    p = argparse.ArgumentParser(description="BioData analysis skill")
    p.add_argument("--input", type=Path)
    p.add_argument("--output", type=Path, default=Path("out"))
    p.add_argument("--demo", action="store_true")
    a = p.parse_args()
    if a.demo:
        df = demo_df()
    elif a.input:
        df = read_input(a.input)
    else:
        p.error("need --input or --demo")
    res = analyze(df, a.output)
    print(f"BioData: {res['rows']} rows x {res['columns']} cols, "
          f"{res['missing_total']} missing values")
    print(f"report   -> {a.output / 'report.md'}")
    print(f"tables   -> {a.output / 'tables'}")
    print(f"figures  -> {a.output / 'figures'}")


if __name__ == "__main__":
    main()
